openapi: 3.2.0
info:
  title: Energy-Charts Prices API
  description: 'Timestamp Format Options


    When specifying timestamps, you can choose from the following three formats:


    ISO 8601 Format:


    This format includes the full date and time, with an optional timezone indicator.'
  termsOfService: https://energy-charts.info/data-protection.html
  contact:
    name: Contact
    url: https://energy-charts.info/contact.html
  license:
    name: Publishing notes
    url: https://energy-charts.info/publishing-notes.html
  version: '1.5'
tags:
- name: Prices
  description: Query price values
paths:
  /price:
    get:
      tags:
      - Prices
      summary: Day Ahead Price
      description: 'Returns the day-ahead spot market price for a specified bidding zone in EUR/MWh.


        Available bidding zones (bzn) are shown above.


        The data for the following bidding zones is licensed as CC BY 4.0 from Bundesnetzagentur | SMARD.de and is published without changes:


        AT (Austria)


        BE (Belgium)


        CH (Switzerland)


        CZ (Czech Republic)


        DE-LU (Germany, Luxembourg)


        DE-AT-LU (Germany, Austria, Luxembourg)


        DK1 (Denmark 1)


        DK2 (Denmark 2)


        FR (France)


        HU (Hungary)


        IT-North (Italy North)


        NL (Netherlands)


        NO2 (Norway 2)


        PL (Poland)


        SE4 (Sweden 4)


        SI (Slovenia)


        The data for the other bidding zones is for private and internal use only. The utilization of any data


        whether in its raw or derived form, for external or commercial purposes is expressly prohibited. Should you require licensing for market-related data, please direct your inquiries to the original data providers, including but not limited to EPEX SPOT SE.


        Response schema:


        ```json

        {

        "license_info": str,

        "unix_seconds": [int],

        "price": [float],

        "unit": str,

        "deprecated": bool

        }

        ```'
      operationId: day_ahead_price_price_get
      parameters:
      - name: bzn
        in: query
        required: false
        schema:
          type: string
          default: DE-LU
          title: Bzn
      - name: start
        in: query
        required: false
        schema:
          type: string
          default: ''
          title: Start
      - name: end
        in: query
        required: false
        schema:
          type: string
          default: ''
          title: End
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceModel'
        '404':
          description: No price data available for that bidding zone/time range
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    PriceModel:
      properties:
        license_info:
          type: string
          title: License Info
        unix_seconds:
          anyOf:
          - items:
              type: integer
            type: array
          - type: 'null'
          title: Unix Seconds
        price:
          anyOf:
          - items:
              anyOf:
              - type: number
              - type: 'null'
            type: array
          - type: 'null'
          title: Price
        unit:
          type: string
          title: Unit
        deprecated:
          type: boolean
          title: Deprecated
      type: object
      required:
      - license_info
      - unit
      - deprecated
      title: PriceModel
